name: Trigger Target Repository Workflow

on:
  push:
    branches:
      - 2024
      - 2025
      - main

jobs:
  trigger-target:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Target Repository
        run: |
          branch=${{ github.ref_name }}
          echo "Triggering workflow for branch: $branch"
          gh workflow run dispatcher.yaml \
            --repo egeakman/target-repo \
            --ref $branch \
            --field branch=$branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
